// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types'; ← Eliminado porque no se usa en JS

const SUPABASE_URL = "https://kolvbhcpywrdfhrlewtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvbHZiaGNweXdyZGZocmxld3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjAzOTgsImV4cCI6MjA2OTE5NjM5OH0.53MptabFakVE1Y5huKEuHjFmT3VQbNTjKaeD2XFmxY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const storage = typeof window !== 'undefined' ? localStorage : undefined;

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   }
// });
